### PR TITLE
Move hardcoded strings to strings.xml

### PR DESCRIPTION
**Pull request by NayakNavin**
moved the string

### CODE REVIEW

**Comment by NayakNavin** [comment]
> Looks fine! Thank you for this PR.

my pleasure.

**Comment by tejasvisoi** [comment]
Would Like To Help In This

**Comment by PatilShreyas** [comment]
It's already in process. You can contribute in different solution.

**Comment by PatilShreyas** [comment]
Thank you @NayakNavin for contribution.

**Pull request merged**
